---
- name: A simple playbook that installs a list of apps
  hosts: all
  gather_facts: false
  
  tasks:
  
  - name: Use the apt package manager
    apt:
      name:
        - figlet
        - cowsay
      state: present
    become: yes