jenkins:
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "danvers"
        name: "Carol Danvers"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "cdanvers@avengers.example"
      - description: "associations:\r\n  - jenkins admin\r\n  - docker management\
          \ team\r\n  - python and ansible programmer\r\nlocation:\r\n  - NYC\r\n\
          relevant URLs:\r\n  - https://alta3.com"
        id: "jarvis"
        name: "Jarvis Edwin"
        properties:
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "JEdwin@stark.example"
        - "apiToken"
      - id: "wanda"
        name: "Wanda Maximoff"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "wmaximoff@avengers.example"
